services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service_account_key.json
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: mariadb:latest
    restart: always
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 10
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
